### PR TITLE
docs: update contributing doc to mention `make boostrap`

### PR DESCRIPTION
**Pull request by lgfa29**
**Description**

`make bootstrap` is a necessary step for development that needs to run at least once.

**Reminders**

- [ ] Add `CHANGELOG.md` entry (not necessary)

### CODE REVIEW

**Review by DerekStrickland — APPROVED** [review]
:shipit:

**Comment by angrycub** [comment]
The `tools` target should be called as a consequence of `make dev` (`dev` -> `lint` -> `tools` -> `lint-deps`).  The `bootstrap` target uses the `tools` target too, it should have been run.  Perhaps we might try a fallback and look in the `$GOHOME/bin` folder in cases where we don't find the tools in the path?

**Comment by lgfa29** [comment]
> The `tools` target should be called as a consequence of `make dev` (`dev` -> `lint` -> `tools` -> `lint-deps`). The `bootstrap` target uses the `tools` target too, it should have been run. Perhaps we might try a fallback and look in the `$GOHOME/bin` folder in cases where we don't find the tools in the path?

The problem is that `tools` take a while to run, even if you already have the tools installed. I'm even considering removing `lint` from `dev` since it also slows down the development flow.

**Comment by lgfa29** [comment]
Updated to mention `$GOHOME/bin`

**Review by jrasell — APPROVED** [review]

**Pull request merged**
